export const marketingSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    branding: {
      type: "array",
      description: "List of EXACTLY 4 distinct brand concepts",
      minItems: 4,
      maxItems: 4,
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: { type: "string" },
          rationale: { type: "string" },
          slogan: { type: "string" },
          description: { type: "string" },
          personality: { type: "string" },
        },
        required: ["name", "rationale", "slogan", "description", "personality"],
      },
    },

    visuals: {
      type: "object",
      additionalProperties: false,
      properties: {
        primaryColor: { type: "string" },
        secondaryColor: { type: "string" },
        fontStyle: { type: "string" },
        logoConcept: { type: "string" },
        logoSvg: { type: "string" },
        moodDescription: { type: "string" },
        visualPersonality: { type: "string" },
        typographyDirection: { type: "string" },
        logoCharacter: { type: "string" },
        graphicStyle: { type: "string" },
      },
      required: [
        "primaryColor",
        "secondaryColor",
        "fontStyle",
        "logoConcept",
        "logoSvg",
        "moodDescription",
        "visualPersonality",
        "typographyDirection",
        "logoCharacter",
        "graphicStyle",
      ],
    },

    website: {
      type: "object",
      additionalProperties: false,
      properties: {
        structure: { type: "array", items: { type: "string" } },
        keyFeatures: { type: "array", items: { type: "string" } },
        seoKeywords: { type: "array", items: { type: "string" } },
        techStack: { type: "array", items: { type: "string" } },
        uiUxTips: { type: "array", items: { type: "string" } },
        platformDefinition: {
          type: "object",
          additionalProperties: false,
          properties: {
            type: { type: "string" },
            primaryGoal: { type: "string" },
            targetDevices: { type: "string" },
          },
          required: ["type", "primaryGoal", "targetDevices"],
        },
        uiMapping: {
          type: "object",
          additionalProperties: false,
          properties: {
            buttonStyle: { type: "string" },
            headerApproach: { type: "string" },
            mobileExperience: { type: "string" },
          },
          required: ["buttonStyle", "headerApproach", "mobileExperience"],
        },
        stackDecision: {
          type: "object",
          additionalProperties: false,
          properties: {
            recommended: { type: "string" },
            codingScore: { type: "integer" },
            wordpressScore: { type: "integer" },
            hivaraIndex: { type: "integer" },
            reasoning: {
              type: "array",
              minItems: 3,
              items: { type: "string" },
            },
            roadmap: {
              type: "array",
              minItems: 3,
              items: { type: "string" },
            },
          },
          required: [
            "recommended",
            "codingScore",
            "wordpressScore",
            "hivaraIndex",
            "reasoning",
            "roadmap",
          ],
        },
        siteArchitecture: {
          type: "object",
          additionalProperties: false,
          properties: {
            corePages: {
              type: "array",
              minItems: 4,
              items: { type: "string" },
            },
            moneyPages: {
              type: "array",
              minItems: 3,
              items: { type: "string" },
            },
            trustPages: {
              type: "array",
              minItems: 3,
              items: { type: "string" },
            },
            featureModules: {
              type: "array",
              minItems: 4,
              items: { type: "string" },
            },
          },
          required: ["corePages", "moneyPages", "trustPages", "featureModules"],
        },
        seoStrategy: {
          type: "object",
          additionalProperties: false,
          properties: {
            keywords: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                properties: {
                  keyword: { type: "string" },
                  difficulty: { type: "string" },
                  attractiveness: { type: "integer" },
                },
                required: ["keyword", "difficulty", "attractiveness"],
              },
            },
            pageMapping: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                properties: {
                  pageName: { type: "string" },
                  seoTitle: { type: "string" },
                  userIntent: { type: "string" },
                },
                required: ["pageName", "seoTitle", "userIntent"],
              },
            },
            contentClusters: {
              type: "array",
              minItems: 3,
              items: {
                type: "object",
                additionalProperties: false,
                properties: {
                  cluster: { type: "string" },
                  intent: { type: "string" },
                  sampleTopics: {
                    type: "array",
                    minItems: 3,
                    items: { type: "string" },
                  },
                },
                required: ["cluster", "intent", "sampleTopics"],
              },
            },
          },
          required: ["keywords", "pageMapping", "contentClusters"],
        },
        healthCheck: {
          type: "object",
          additionalProperties: false,
          properties: {
            seo: { type: "string" },
            performance: { type: "string" },
            conversionReadiness: { type: "string" },
          },
          required: ["seo", "performance", "conversionReadiness"],
        },
      },
      required: [
        "structure",
        "keyFeatures",
        "seoKeywords",
        "techStack",
        "uiUxTips",
        "platformDefinition",
        "uiMapping",
        "stackDecision",
        "siteArchitecture",
        "seoStrategy",
        "healthCheck",
      ],
    },

    marketIntel: {
      type: "object",
      description: "Strategic market intelligence and competitive analysis",
      additionalProperties: false,
      properties: {
        marketSize: {
          type: "object",
          additionalProperties: false,
          properties: {
            tam: { type: "string" },
            sam: { type: "string" },
            som: { type: "string" },
          },
          required: ["tam", "sam", "som"],
        },
        competitors: {
          type: "array",
          minItems: 3,
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              name: { type: "string" },
              strength: { type: "string" },
              weakness: { type: "string" },
              differentiation: { type: "string" },
            },
            required: ["name", "strength", "weakness", "differentiation"],
          },
        },
        swot: {
          type: "object",
          additionalProperties: false,
          properties: {
            strengths: { type: "array", minItems: 3, items: { type: "string" } },
            weaknesses: { type: "array", minItems: 3, items: { type: "string" } },
            opportunities: { type: "array", minItems: 3, items: { type: "string" } },
            threats: { type: "array", minItems: 3, items: { type: "string" } },
          },
          required: ["strengths", "weaknesses", "opportunities", "threats"],
        },
        competitiveAdvantage: { type: "string" },
        positioningStatement: { type: "string" },
      },
      required: [
        "marketSize",
        "competitors",
        "swot",
        "competitiveAdvantage",
        "positioningStatement",
      ],
    },

    social: {
      type: "object",
      additionalProperties: false,
      properties: {
        voiceAndTone: {
          type: "object",
          additionalProperties: false,
          properties: {
            formality: { type: "string" },
            boldness: { type: "string" },
            purpose: { type: "string" },
            vibe: { type: "string" },
          },
          required: ["formality", "boldness", "purpose", "vibe"],
        },
        weeklyCalendar: {
          type: "array",
          minItems: 5,
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              day: { type: "string" },
              type: { type: "string", enum: ["Reel", "Post", "Story"] },
              title: { type: "string" },
              description: { type: "string" },
              hook: { type: "string" },
              scenario: { type: "string" },
              goal: { type: "string" },
              visualDescription: { type: "string" },
            },
            required: [
              "day",
              "type",
              "title",
              "description",
              "hook",
              "scenario",
              "goal",
              "visualDescription",
            ],
          },
        },
        pillars: {
          type: "array",
          minItems: 4,
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              title: { type: "string" },
              description: { type: "string" },
            },
            required: ["title", "description"],
          },
        },
        growthHacks: {
          type: "array",
          minItems: 4,
          items: { type: "string" },
        },
        hashtagClusters: {
          type: "array",
          minItems: 3,
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              theme: { type: "string" },
              hashtags: {
                type: "array",
                minItems: 5,
                items: { type: "string" },
              },
            },
            required: ["theme", "hashtags"],
          },
        },
        iranianInfluencers: {
          type: "array",
          minItems: 3,
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              name: { type: "string" },
              niche: { type: "string" },
              collaborationIdea: { type: "string" },
            },
            required: ["name", "niche", "collaborationIdea"],
          },
        },
      },
      required: [
        "voiceAndTone",
        "weeklyCalendar",
        "pillars",
        "growthHacks",
        "hashtagClusters",
        "iranianInfluencers",
      ],
    },

    growth: {
      type: "object",
      additionalProperties: false,
      properties: {
        challengeTitle: { type: "string" },
        challengeDescription: { type: "string" },
        expectedResult: { type: "string" },
        viralIdea: { type: "string" },
        mentorAdvice: { type: "string" },
        goal: { type: "string" },
        timeframe: { type: "string" },
        targetAudience: { type: "string" },
        keyCampaignMessage: { type: "string" },
        acquisitionMechanism: { type: "string" },
        engagementMechanism: { type: "string" },
        conversionMechanism: { type: "string" },
        cta: { type: "string" },
        incentiveLevers: { type: "string" },
        viralTriggers: { type: "string" },
        referralSystem: { type: "string" },
        gamification: { type: "string" },
        growthChannels: { type: "array", items: { type: "string" } },
        partnerships: { type: "string" },
        reengagement: { type: "string" },
        requiredResources: { type: "string" },
        executionCost: { type: "string" },
        kpis: { type: "array", items: { type: "string" } },
        resultPrediction: { type: "string" },
        scalabilityPlan: { type: "string" },
      },
      required: [
        "challengeTitle",
        "challengeDescription",
        "expectedResult",
        "viralIdea",
        "mentorAdvice",
        "goal",
        "timeframe",
        "targetAudience",
        "keyCampaignMessage",
        "acquisitionMechanism",
        "engagementMechanism",
        "conversionMechanism",
        "cta",
        "incentiveLevers",
        "viralTriggers",
        "referralSystem",
        "gamification",
        "growthChannels",
        "partnerships",
        "reengagement",
        "requiredResources",
        "executionCost",
        "kpis",
        "resultPrediction",
        "scalabilityPlan",
      ],
    },

    evaluation: {
      type: "object",
      description: "Final verdict by Tahmtan, Hivara's chief AI investment judge",
      additionalProperties: false,
      properties: {
        score: { type: "integer" },
        feedback: { type: "string" },
        investmentOffer: { type: "boolean" },
        investmentPercentage: { type: "integer" },
        marketScore: { type: "integer" },
        brandScore: { type: "integer" },
        growthScore: { type: "integer" },
        executionScore: { type: "integer" },
        riskScore: { type: "integer" },
        strengthsSummary: { type: "string" },
        riskFactors: {
          type: "array",
          minItems: 3,
          items: { type: "string" },
        },
        milestonesForInvestment: {
          type: "array",
          minItems: 3,
          items: { type: "string" },
        },
        verdict: { type: "string" },
        investmentDecision: { type: "string" },
      },
      required: [
        "score",
        "feedback",
        "investmentOffer",
        "investmentPercentage",
        "marketScore",
        "brandScore",
        "growthScore",
        "executionScore",
        "riskScore",
        "strengthsSummary",
        "riskFactors",
        "milestonesForInvestment",
        "verdict",
        "investmentDecision",
      ],
    },

    summary: { type: "string" },
  },

  required: [
    "branding",
    "visuals",
    "website",
    "marketIntel",
    "social",
    "growth",
    "evaluation",
    "summary",
  ],
};
