import { Geist, Geist_Mono } from "next/font/google";
import "../../styles/globals.css";
import "../../styles/style.css";
import { UserProvider } from "@/context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased rtl`}
      >
        <link
          rel="stylesheet"
          href="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/styles.css"
        />
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
